name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Build APK
        run: |
          mkdir -p android/app/build/outputs/apk/release
          gradle wrapper
          cd android
          ./gradlew assembleRelease
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/check-van-level.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: check-van-level.apk
          path: android/app/build/outputs/apk/release/check-van-level.apk
